# Generated by Django 6.0.3 on 2026-03-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilite',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('vuln_status', models.CharField(blank=True, max_length=50, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('base_score_v2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('severity_v2', models.CharField(blank=True, max_length=20, null=True)),
                ('vector_string_v2', models.CharField(blank=True, max_length=100, null=True)),
                ('base_score_v3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('severity_v3', models.CharField(blank=True, max_length=20, null=True)),
                ('vector_string_v3', models.CharField(blank=True, max_length=100, null=True)),
                ('exploitability_score_v3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('impact_score_v3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Vulnérabilité',
                'verbose_name_plural': 'Vulnérabilités',
                'indexes': [models.Index(fields=['id'], name='vulnerabili_id_374131_idx'), models.Index(fields=['published_date'], name='vulnerabili_publish_a43f17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='vulnerabilities.vulnerabilite')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
            },
        ),
        migrations.CreateModel(
            name='FaiblesseCWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.CharField(max_length=20)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faiblesses', to='vulnerabilities.vulnerabilite')),
            ],
            options={
                'verbose_name': 'Faiblesse CWE',
                'verbose_name_plural': 'Faiblesses CWE',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
                ('version_start_incl', models.CharField(blank=True, max_length=50, null=True)),
                ('version_start_excl', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_incl', models.CharField(blank=True, max_length=50, null=True)),
                ('version_end_excl', models.CharField(blank=True, max_length=50, null=True)),
                ('vulnerable', models.BooleanField(default=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='vulnerabilities.vulnerabilite')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'indexes': [models.Index(fields=['criteria'], name='vulnerabili_criteri_44ce4a_idx')],
            },
        ),
    ]
