# Generated by Django 5.2.12 on 2026-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_alter_configuration_id_alter_faiblessecwe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faiblessecwe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CVEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('cvss_v3_score', models.FloatField(blank=True, null=True)),
                ('cvss_v3_vector', models.CharField(blank=True, default='', max_length=100)),
                ('cvss_v3_severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cvss_v2_score', models.FloatField(blank=True, null=True)),
                ('cvss_v2_severity', models.CharField(blank=True, default='', max_length=20)),
                ('cwe_ids', models.CharField(blank=True, default='', max_length=255)),
                ('affected_products', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('has_exploit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['cvss_v3_severity'], name='vulnerabili_cvss_v3_148d55_idx'), models.Index(fields=['published'], name='vulnerabili_publish_eb98b5_idx'), models.Index(fields=['has_exploit'], name='vulnerabili_has_exp_631e42_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExploitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploit_id', models.IntegerField(db_index=True, unique=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_published', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('exploit_type', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('port', models.CharField(blank=True, default='', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('cve_codes', models.CharField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-date_published'],
                'indexes': [models.Index(fields=['platform'], name='vulnerabili_platfor_e5b79d_idx'), models.Index(fields=['exploit_type'], name='vulnerabili_exploit_5f70ac_idx'), models.Index(fields=['date_published'], name='vulnerabili_date_pu_25a3ab_idx')],
            },
        ),
    ]
