# Generated by Django 5.2.12 on 2026-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_alter_configuration_id_alter_faiblessecwe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cveentry',
            name='cvss_v3_severity',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
