# Generated by Django 6.0.2 on 2026-02-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('cpe', models.CharField(blank=True, max_length=255, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('total_ports_scanned', models.IntegerField(default=0)),
                ('closed_ports', models.IntegerField(default=0)),
                ('filtered_ports', models.IntegerField(default=0)),
                ('open_ports', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('begin_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('is_web_service', models.BooleanField(default=False)),
                ('is_potentially_risky', models.BooleanField(default=False)),
                ('banner', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scans.hostinfo')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scans.scan')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_info', to='scans.scan'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('exploit_available', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.hostinfo')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.port')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scan')),
            ],
        ),
    ]
