# Generated by Django 5.2.12 on 2026-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_hostinfo_business_criticality_scan_scan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permanentscan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permanentscan',
            name='scan_type',
            field=models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('service', 'Service Scan')], default='full', max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
