# Generated by Django 5.2.12 on 2026-04-02 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_scan_permanent_scan_alter_hostinfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='speed',
            field=models.CharField(default='-T3', max_length=20),
        ),
        migrations.CreateModel(
            name='WebScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('findings_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_scan_results', to='scans.hostinfo')),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_scan_results', to='scans.port')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_scan_results', to='scans.scan')),
            ],
            options={
                'db_table': 'web_scan_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('whatweb', 'WhatWeb'), ('nikto', 'Nikto'), ('gobuster', 'Gobuster'), ('headers', 'Headers HTTP'), ('manual', 'Manuel')], max_length=20)),
                ('finding_type', models.CharField(choices=[('vulnerability', 'Vulnérabilité'), ('misconfiguration', 'Mauvaise configuration'), ('missing_header', 'Header manquant'), ('dangerous_header', 'Header dangereux'), ('enumeration', 'Énumération'), ('technology', 'Technologie détectée'), ('cookie', 'Problème cookie'), ('info', 'Information')], default='info', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cve_id', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('evidence', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('remediation', models.TextField(blank=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_findings', to='scans.hostinfo')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_findings', to='scans.scan')),
                ('web_scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.webscanresult')),
            ],
            options={
                'db_table': 'web_findings',
                'ordering': ['-severity', '-cvss_score', 'created_at'],
                'indexes': [models.Index(fields=['scan', 'severity'], name='web_finding_scan_id_0a40a1_idx'), models.Index(fields=['scan', 'source'], name='web_finding_scan_id_bc1b9c_idx'), models.Index(fields=['cve_id'], name='web_finding_cve_id_c3d318_idx')],
            },
        ),
    ]
